### ISSUE TITLE
Inclusion of SIkJalpha model 

### ISSUE THREAD

**Issue by scc-usc** [pyliu47/covidcompare#2]
Hi all,

I would like to request the inclusion of our model SIkJalpha in your comparison framework. 
Our forecasts starting from May can be found at https://github.com/scc-usc/ReCOVER-COVID-19/tree/master/results/historical_forecasts 
The folder provides date-stamped forecasts for reported cases and deaths in countries and US states. We are using JHU CSSE data. The repo contains all our code for forecasting and for our interactive visualization: https://scc-usc.github.io/ReCOVER-COVID-19/
Details of our approach can be found at: https://arxiv.org/abs/2007.05180
Please feel free to contact me if you have any questions. I appreciate your efforts in putting together this comparison framework.

Thanks,
Ajitesh
ajiteshs@usc.edu

**Comment by pyliu47** [comment]
Hi Ajitesh,

Thanks so much for the message and for preparing the results in a way that facilitates easy incorporation into our framework. We have since included your model and the historical estimates. Please find the updated data and estimates in our most recent push. 

Warmly,
Patty
