### ISSUE TITLE
Error checking for inputs from other groups

### ISSUE THREAD

**Issue by rexdouglass** [pyliu47/covidcompare#3]
In 1_pull_data.r

> ## Collate everything together
> df <- lapply(db$model, function(model) {
>   path <- paste0(data.root, "/", model)
>   files <- list.files(path, full.name = T)
>   df <- lapply(files, fread) %>% rbindlist(., fill = T)
> }) %>% rbindlist(., fill = T)

Fails because your input data from other groups are dirty. Specifically sikjalpha looks like they suffered a bad git merge on their end

> Warning messages:
> 1: In FUN(X[[i]], ...) :
>   Stopped early on line 73216. Expected 7 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<<<<<<<< HEAD>>
> 2: In FUN(X[[i]], ...) :
>   Stopped early on line 134. Expected 7 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<<<<<<<< HEAD>>
> 3: In FUN(X[[i]], ...) :
>   Stopped early on line 135. Expected 7 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<<<<<<<< HEAD>>
> 4: In FUN(X[[i]], ...) :
>   Stopped early on line 136. Expected 7 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<<<<<<<< HEAD>>
> 5: In FUN(X[[i]], ...) :
>   Stopped early on line 137. Expected 7 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<<<<<<<< HEAD>>

Correction, that's the warning. The failure is from item 136 of delphi. where the date column is text and not dates.
[[136]]
      location_name       date deaths model_date  model
   1:       Germany 2020-03-01      0     test-- delphi
   2:       Germany 2020-03-02      1     test-- delphi

Which throws an error for rbindlist.
> rbindlist(df_list, fill=T)
Error in rbindlist(df_list, fill = T) : 
  Class attribute on column 4 of item 136 does not match with column 4 of item 1.

**Comment by pyliu47** [comment]
Hi Rex--thanks for the message and apologies for such an untimely response. Should now be fixed with the most recent push. To circumvent large file issues, we have introduced a function `collate.data()`, sourced from `_collate.r`, which will compile and clean the data.
