### ISSUE TITLE
Displaying Imperial Median prediction rather than mean

### ISSUE THREAD

**Issue by OJWatson** [pyliu47/covidcompare#4]
Hey there, 

Came across https://covidcompare.io/ today - very neat and really clear presentation. 

Hoping you could swap out Imperial's results to use the median (y_median) instead of the mean. The median is more correct for summarising our stochastic results given the negative binomial used to describe daily deaths in our fitting. E.g. for USA on our last fit (12-12-2020) median 2541 deaths vs mean 2786 deaths. 

All the best, 

OJ

**Comment by pyliu47** [comment]
Hi OJ--thanks for the message and for clarifying. We've since swapped out the median for the mean for all historical estimates. This is also reflected on [covidcompare.io](https://covidcompare.io). 

Warmly,
Patty
