### ISSUE TITLE
Imperial old model runs moved location

### ISSUE THREAD

**Issue by OJWatson** [pyliu47/covidcompare#5]
Hi, 

The old model runs are now at: https://mrcdata.dide.ic.ac.uk/global-lmic-reports/

We will be periodically be moving old model runs to this location as we keep running out of space on our Github for hosting all of them.

All the best, 

OJ

**Comment by pyliu47** [comment]
Hi OJ,

Thanks kindly for reaching out and giving us a heads up. We've since updated the code to direct to the old model runs in addition to the Github repo. Changes are in the following commit: https://github.com/pyliu47/covidcompare/commit/467fc53ff15b3295ceffb0322d5aaac3fd55e6f1

Warmly,
Patty
